### PR TITLE
Adding webvr category and finalizing article

### PR DESCRIPTION
**Pull request by streetalchemist**
@jdevl READY TO REVIEW!

### CODE REVIEW

**Comment by streetalchemist** [comment]
also: if you don't particularly feel like it i'm happy to just push it, lol

**Comment by jdevl** [comment]
@streetalchemist a link update in WebVR paragraph - make the whole phrase "our WebVR tribute to The Snowman" link to our snowman page

**Comment by jdevl** [comment]
also above that, change the "our" link to read "our team's" to give more context

**Comment by jdevl** [comment]
text update - 2nd to last paragraph "finnish" should be capitalized to "Finnish" band Nightwish

**Comment by jdevl** [comment]
Final sentence - make the entire sentence a link and add a period to the end.

**Pull request merged**
